# Generated by Django 5.2.7 on 2025-12-05 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecioBalon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('10kg', '10 kg'), ('15kg', '15 kg'), ('45kg', '45 kg')], max_length=10, unique=True)),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('activo', models.BooleanField(default=True)),
                ('actualizado_el', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Precio de Balón',
                'verbose_name_plural': 'Precios de Balones',
            },
        ),
    ]
