# Generated by Django 5.2.7 on 2025-12-05 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockups', '0002_preciobalon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preciobalon',
            name='tipo',
            field=models.CharField(choices=[('5kg', '5 kg'), ('11kg', '11 kg'), ('15kg', '15 kg'), ('45kg', '45 kg')], max_length=10, unique=True),
        ),
    ]
