# Generated by Django 5.2.7 on 2025-12-06 05:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockups', '0003_alter_preciobalon_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='preciobalon',
            name='actualizado_por',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='telefonista',
        ),
        migrations.AddField(
            model_name='pedido',
            name='registrador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='sector',
            field=models.CharField(blank=True, help_text='Ej: Población Dintrans, Machalí Alto, Villa Los Tilos, Gultro...', max_length=100, verbose_name='Sector / Población'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='direccion_entrega',
            field=models.CharField(blank=True, help_text='Ej: Los Álamos 123, casa esquina roja, frente al colegio', max_length=250, verbose_name='Dirección o referencia'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_ruta', 'En ruta'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia')], default='efectivo', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='monto',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Monto total'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='origen',
            field=models.CharField(choices=[('telefono', 'Teléfono'), ('local', 'Local')], default='telefono', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('telefonista', 'Telefonista'), ('bodeguero', 'Bodeguero'), ('camionero', 'Camionero'), ('jefe', 'Jefe'), ('admin', 'Administrador')], default='telefonista', max_length=20, verbose_name='Rol'),
        ),
        migrations.CreateModel(
            name='TipoBalon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamaño', models.CharField(help_text='Ej: 5kg, 15kg, 45kg', max_length=10, unique=True, verbose_name='Tamaño')),
                ('precio', models.DecimalField(decimal_places=0, default=0, help_text='Precio entero en pesos chilenos', max_digits=10, verbose_name='Precio actual (CLP)')),
                ('activo', models.BooleanField(default=True, verbose_name='Disponible para venta')),
                ('actualizado_el', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Tipo de Balón',
                'verbose_name_plural': 'Tipos de Balones',
                'ordering': ['tamaño'],
            },
        ),
        migrations.CreateModel(
            name='HistorialPrecioBalon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_anterior', models.DecimalField(decimal_places=0, max_digits=10)),
                ('precio_nuevo', models.DecimalField(decimal_places=0, max_digits=10)),
                ('activo_anterior', models.BooleanField()),
                ('activo_nuevo', models.BooleanField()),
                ('fecha_cambio', models.DateTimeField(default=django.utils.timezone.now)),
                ('cambiado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Cambiado por')),
                ('tipo_balón', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='mockups.tipobalon')),
            ],
            options={
                'verbose_name': 'Cambio de Precio',
                'verbose_name_plural': 'Historial de Precios',
                'ordering': ['-fecha_cambio'],
            },
        ),
        migrations.AlterField(
            model_name='pedido',
            name='balon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mockups.tipobalon', verbose_name='Tipo de balón'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['fecha'], name='mockups_ped_fecha_49bdbd_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['origen'], name='mockups_ped_origen_a47a8e_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['estado'], name='mockups_ped_estado_372ad8_idx'),
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='PrecioBalon',
        ),
    ]
