# Generated by Django 5.2.7 on 2025-12-07 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockups', '0004_remove_pedido_cliente_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipobalon',
            options={'ordering': ['peso_neto_gas'], 'verbose_name': 'Tipo de Balon', 'verbose_name_plural': 'Tipos de Balones'},
        ),
        migrations.RemoveField(
            model_name='tipobalon',
            name='tamaño',
        ),
        migrations.AddField(
            model_name='tipobalon',
            name='nombre',
            field=models.CharField(blank=True, help_text='Ej: Gas de 5 kg, Gas de 15 kg', max_length=50, null=True, unique=True, verbose_name='Nombre comercial'),
        ),
        migrations.AddField(
            model_name='tipobalon',
            name='peso_neto_gas',
            field=models.PositiveIntegerField(blank=True, help_text='Cantidad real de gas licuado (sin envase)', null=True, verbose_name='Peso neto de gas (kg)'),
        ),
        migrations.AlterField(
            model_name='tipobalon',
            name='actualizado_el',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tipobalon',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tipobalon',
            name='precio',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Precio actual (CLP)'),
        ),
    ]
