# Generated by Django 5.2.9 on 2026-01-13 12:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockups', '0005_alter_tipobalon_options_remove_tipobalon_tamaño_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='entregador',
            field=models.ForeignKey(blank=True, help_text='Camionero que tomó y entregó el pedido', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_entregados', to=settings.AUTH_USER_MODEL, verbose_name='Entregado por'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_ruta', 'En ruta'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de registro'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia')], default='efectivo', max_length=20, verbose_name='Método de pago'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='origen',
            field=models.CharField(choices=[('telefono', 'Teléfono'), ('local', 'Venta en local')], default='telefono', max_length=20, verbose_name='Origen del pedido'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['registrador'], name='mockups_ped_registr_b26b12_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['entregador'], name='mockups_ped_entrega_5c30fe_idx'),
        ),
    ]
