# Generated by Django 5.2.9 on 2026-01-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockups', '0006_pedido_entregador_alter_pedido_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='origen',
            field=models.CharField(choices=[('telefono', 'Teléfono'), ('local', 'Venta en local'), ('tarreo', 'venta por tarreo'), ('venta_extra', 'venta añadida durante la entrega')], default='telefono', max_length=20, verbose_name='Origen del pedido'),
        ),
    ]
