# Generated by Django 5.2.9 on 2026-01-14 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockups', '0007_alter_pedido_origen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historialpreciobalon',
            options={'ordering': ['-fecha_cambio'], 'verbose_name': 'Historial de precio', 'verbose_name_plural': 'Historial de precios'},
        ),
        migrations.AlterModelOptions(
            name='tipobalon',
            options={'ordering': ['peso_neto_gas'], 'verbose_name': 'Tipo de balón', 'verbose_name_plural': 'Tipos de balones'},
        ),
        migrations.RemoveField(
            model_name='historialpreciobalon',
            name='activo_nuevo',
        ),
        migrations.RemoveField(
            model_name='historialpreciobalon',
            name='cambiado_por',
        ),
        migrations.RemoveField(
            model_name='historialpreciobalon',
            name='precio_anterior',
        ),
        migrations.RemoveField(
            model_name='historialpreciobalon',
            name='precio_nuevo',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='balon',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='cantidad_balon',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='monto',
        ),
        migrations.RemoveField(
            model_name='tipobalon',
            name='precio',
        ),
        migrations.AddField(
            model_name='historialpreciobalon',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historialpreciobalon',
            name='precio_compra_anterior',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historialpreciobalon',
            name='precio_domicilio_anterior',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historialpreciobalon',
            name='precio_local_anterior',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='ganancia_total',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Ganancia total'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='monto_total',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Monto total venta'),
        ),
        migrations.AddField(
            model_name='tipobalon',
            name='precio_compra',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Costo real para KIM GAS (proveedor)', max_digits=10, verbose_name='Precio de compra (CLP)'),
        ),
        migrations.AddField(
            model_name='tipobalon',
            name='precio_domicilio',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Precio para pedidos telefónicos, tarreo o entregas a domicilio', max_digits=10, verbose_name='Precio venta domicilio (CLP)'),
        ),
        migrations.AddField(
            model_name='tipobalon',
            name='precio_local',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Precio al público en bodega / venta directa', max_digits=10, verbose_name='Precio venta local (CLP)'),
        ),
        migrations.AlterField(
            model_name='historialpreciobalon',
            name='tipo_balón',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_precios', to='mockups.tipobalon'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='direccion_entrega',
            field=models.CharField(blank=True, max_length=250, verbose_name='Dirección o referencia'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='entregador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_entregados', to=settings.AUTH_USER_MODEL, verbose_name='Entregado por'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_ruta', 'En ruta'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia')], default='efectivo', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='origen',
            field=models.CharField(choices=[('telefono', 'Teléfono / Domicilio'), ('local', 'Venta en local'), ('tarreo', 'Venta por tarreo'), ('venta_extra', 'Venta adicional en entrega')], default='telefono', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='registrador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='sector',
            field=models.CharField(blank=True, max_length=100, verbose_name='Sector / Población'),
        ),
        migrations.AlterField(
            model_name='tipobalon',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Última actualización por'),
        ),
        migrations.AlterField(
            model_name='tipobalon',
            name='nombre',
            field=models.CharField(default=0, help_text='Ej: Gas 5 kg, Gas 11 kg, Gas 15 kg, Gas 45 kg', max_length=50, unique=True, verbose_name='Nombre comercial'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tipobalon',
            name='peso_neto_gas',
            field=models.PositiveIntegerField(default=0, help_text='Cantidad real de gas licuado (sin envase)', verbose_name='Peso neto de gas (kg)'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('precio_venta_unitario', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Precio venta unitario')),
                ('precio_compra_unitario', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Precio compra unitario')),
                ('balon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mockups.tipobalon', verbose_name='Tipo de balón')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='mockups.pedido')),
            ],
            options={
                'verbose_name': 'Detalle de pedido',
                'verbose_name_plural': 'Detalles de pedidos',
                'ordering': ['balon__peso_neto_gas'],
            },
        ),
    ]
