# Generated by Django 5.2.9 on 2026-01-16 17:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockups', '0009_historialestadopedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='SobreDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha del sobre')),
                ('tipo', models.CharField(choices=[('camion', 'Camión'), ('bodega', 'Bodega/local')], default='camion', max_length=20, verbose_name='Tipo de sobre')),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('actualizado_el', models.DateTimeField(auto_now=True)),
                ('monto_calculado_app', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Monto según pedidos en app')),
                ('monto_declarado', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Monto declarado/ajustado')),
                ('diferencia', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Diferencia (ajuste)')),
                ('notas', models.TextField(blank=True, verbose_name='Notas / motivo del ajuste')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sobres_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por (bodeguero/jefe)')),
                ('trabajador', models.ForeignKey(limit_choices_to={'rol__in': ['camionero', 'bodeguero']}, on_delete=django.db.models.deletion.PROTECT, related_name='sobres', to=settings.AUTH_USER_MODEL, verbose_name='Trabajador (camionero o bodeguero)')),
            ],
            options={
                'verbose_name': 'Sobre diario',
                'verbose_name_plural': 'Sobres diarios',
                'ordering': ['-fecha', 'trabajador__username'],
                'unique_together': {('fecha', 'trabajador', 'tipo')},
            },
        ),
        migrations.CreateModel(
            name='LineaSobre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_calculada', models.PositiveIntegerField(default=0, verbose_name='Cantidad según app')),
                ('cantidad_declarada', models.PositiveIntegerField(default=0, verbose_name='Cantidad declarada')),
                ('precio_venta_unitario', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('balon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mockups.tipobalon', verbose_name='Tipo de balón')),
                ('sobre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='mockups.sobrediario')),
            ],
            options={
                'ordering': ['balon__peso_neto_gas'],
                'unique_together': {('sobre', 'balon')},
            },
        ),
    ]
