# Generated by Django 5.2.9 on 2026-01-16 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockups', '0010_sobrediario_lineasobre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sobrediario',
            name='notas',
        ),
        migrations.AddField(
            model_name='lineasobre',
            name='nota',
            field=models.TextField(blank=True, verbose_name='Motivo del ajuste en esta línea'),
        ),
        migrations.AddField(
            model_name='sobrediario',
            name='nota',
            field=models.TextField(blank=True, verbose_name='Motivo del ajuste en esta línea'),
        ),
    ]
