# Generated by Django 5.2.9 on 2026-01-16 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockups', '0011_remove_sobrediario_notas_lineasobre_nota_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sobrediario',
            name='trabajador',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol__in': ['camionero', 'bodeguero']}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sobres', to=settings.AUTH_USER_MODEL, verbose_name='Trabajador (camionero o bodeguero)'),
        ),
    ]
