# Generated by Django 5.2.9 on 2026-01-20 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockups', '0012_alter_sobrediario_trabajador'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialCambioPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del cambio')),
                ('descripcion', models.TextField(help_text='Descripción automática de los cambios realizados', verbose_name='Qué cambió')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_cambios', to='mockups.pedido')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que editó')),
            ],
            options={
                'verbose_name': 'Historial de Cambio en Pedido',
                'verbose_name_plural': 'Historial de Cambios en Pedidos',
                'ordering': ['-fecha'],
            },
        ),
    ]
