# Generated by Django 5.2.9 on 2026-01-26 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockups', '0013_historialcambiopedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_precio', models.CharField(choices=[('compra', 'Compra'), ('local', 'Local'), ('domicilio', 'Domicilio')], max_length=10, verbose_name='Tipo de Precio')),
                ('precio_anterior', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Precio Anterior')),
                ('precio_nuevo', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Precio Nuevo')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del Cambio')),
                ('balon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_precios', to='mockups.tipobalon')),
                ('cambiado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Cambiado por')),
            ],
            options={
                'verbose_name': 'Historial de Precio',
                'verbose_name_plural': 'Historial de Precios',
                'ordering': ['-fecha_cambio'],
            },
        ),
        migrations.DeleteModel(
            name='HistorialPrecioBalon',
        ),
    ]
