# Generated by Django 5.2.9 on 2026-01-26 14:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockups', '0014_historialprecio_delete_historialpreciobalon'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialPrecioBalon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_compra_anterior', models.DecimalField(decimal_places=0, max_digits=10)),
                ('precio_local_anterior', models.DecimalField(decimal_places=0, max_digits=10)),
                ('precio_domicilio_anterior', models.DecimalField(decimal_places=0, max_digits=10)),
                ('activo_anterior', models.BooleanField()),
                ('fecha_cambio', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tipo_balón', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_precios', to='mockups.tipobalon')),
            ],
            options={
                'verbose_name': 'Historial de precio',
                'verbose_name_plural': 'Historial de precios',
                'ordering': ['-fecha_cambio'],
            },
        ),
        migrations.DeleteModel(
            name='HistorialPrecio',
        ),
    ]
