# Generated by Django 5.2.9 on 2026-01-26 15:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockups', '0015_historialpreciobalon_delete_historialprecio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historialpreciobalon',
            options={'ordering': ['-fecha_cambio'], 'verbose_name': 'Historial de Precio de Balón', 'verbose_name_plural': 'Historial de Precios de Balones'},
        ),
        migrations.RemoveField(
            model_name='historialpreciobalon',
            name='tipo_balón',
        ),
        migrations.AddField(
            model_name='historialpreciobalon',
            name='nombre_balon',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del Balón (snapshot)'),
        ),
        migrations.AlterField(
            model_name='historialpreciobalon',
            name='activo_anterior',
            field=models.BooleanField(verbose_name='Disponible Anterior'),
        ),
        migrations.AlterField(
            model_name='historialpreciobalon',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AlterField(
            model_name='historialpreciobalon',
            name='fecha_cambio',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha del Cambio'),
        ),
        migrations.AlterField(
            model_name='historialpreciobalon',
            name='precio_compra_anterior',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Precio Compra Anterior'),
        ),
        migrations.AlterField(
            model_name='historialpreciobalon',
            name='precio_domicilio_anterior',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Precio Domicilio Anterior'),
        ),
        migrations.AlterField(
            model_name='historialpreciobalon',
            name='precio_local_anterior',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Precio Local Anterior'),
        ),
    ]
