# Generated by Django 5.2.9 on 2026-01-28 16:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockups', '0016_alter_historialpreciobalon_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sobrediario',
            name='cerrado',
            field=models.BooleanField(default=False, verbose_name='Sobre cerrado/finalizado'),
        ),
        migrations.AddField(
            model_name='sobrediario',
            name='declarado_el',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de declaración/cierre'),
        ),
        migrations.AddField(
            model_name='sobrediario',
            name='kilometraje_camion',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Lectura del odómetro al momento de cerrar el sobre', verbose_name='Kilometraje total del camión'),
        ),
        migrations.AddField(
            model_name='sobrediario',
            name='nota_cierre',
            field=models.TextField(blank=True, verbose_name='Nota al cerrar el sobre'),
        ),
        migrations.AlterField(
            model_name='sobrediario',
            name='actualizado_el',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
        migrations.AlterField(
            model_name='sobrediario',
            name='creado_el',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha/hora de creación'),
        ),
        migrations.AlterField(
            model_name='sobrediario',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha del sobre (día de las ventas)'),
        ),
        migrations.AlterField(
            model_name='sobrediario',
            name='nota',
            field=models.TextField(blank=True, verbose_name='Nota general del sobre'),
        ),
    ]
