# Generated by Django 5.2.9 on 2026-01-29 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mockups', '0017_sobrediario_cerrado_sobrediario_declarado_el_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sobrediario',
            options={'ordering': ['-fecha', '-creado_el'], 'verbose_name': 'Sobre diario', 'verbose_name_plural': 'Sobres diarios'},
        ),
    ]
