# Generated by Django 5.2.9 on 2026-01-29 22:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockups', '0018_alter_sobrediario_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sobrediario',
            options={'ordering': ['-fecha', 'trabajador__username'], 'verbose_name': 'Sobre diario', 'verbose_name_plural': 'Sobres diarios'},
        ),
        migrations.AlterField(
            model_name='sobrediario',
            name='actualizado_el',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sobrediario',
            name='creado_el',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sobrediario',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha del sobre'),
        ),
        migrations.AlterField(
            model_name='sobrediario',
            name='nota',
            field=models.TextField(blank=True, verbose_name='Motivo del ajuste en esta línea'),
        ),
    ]
