# Generated by Django 5.2.9 on 2026-01-30 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockups', '0019_alter_sobrediario_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineaGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción')),
                ('monto', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Monto')),
                ('nota', models.TextField(blank=True, verbose_name='Nota')),
                ('sobre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='mockups.sobrediario')),
            ],
            options={
                'verbose_name': 'Línea de Gasto Extra',
                'verbose_name_plural': 'Líneas de Gastos Extras',
                'ordering': ['-monto'],
            },
        ),
        migrations.CreateModel(
            name='LineaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pago', models.CharField(choices=[('abono', 'Abono Caja'), ('transferencia', 'Transferencia'), ('visa', 'Visa'), ('cheque', 'Cheque'), ('otro', 'Otro')], default='otro', max_length=20, verbose_name='Tipo de Pago')),
                ('monto', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Monto')),
                ('referencia', models.CharField(blank=True, max_length=100, verbose_name='Referencia/Nota')),
                ('sobre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='mockups.sobrediario')),
            ],
            options={
                'verbose_name': 'Línea de Pago No Efectivo',
                'verbose_name_plural': 'Líneas de Pagos No Efectivos',
                'ordering': ['-monto'],
            },
        ),
    ]
