# Generated by Django 5.2.9 on 2026-02-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockups', '0020_lineagasto_lineapago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineapago',
            name='tipo_pago',
            field=models.CharField(choices=[('abono', 'Abono Caja'), ('transferencia', 'Transferencia'), ('visa', 'Visa'), ('cheque', 'Cheque'), ('efectivo', 'Efectivo'), ('otro', 'Otro')], default='otro', max_length=20, verbose_name='Tipo de Pago'),
        ),
    ]
