# Generated by Django 5.2.9 on 2026-02-10 14:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockups', '0021_alter_lineapago_tipo_pago'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sobrediario',
            options={'ordering': ['-fecha_correspondiente', '-fecha'], 'verbose_name': 'Sobre diario', 'verbose_name_plural': 'Sobres diarios'},
        ),
        migrations.AlterUniqueTogether(
            name='sobrediario',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='sobrediario',
            name='fecha_correspondiente',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha a la que corresponde'),
        ),
        migrations.AlterField(
            model_name='sobrediario',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sobres_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por (bodeguero/jefe)'),
        ),
        migrations.AlterField(
            model_name='sobrediario',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación'),
        ),
    ]
