# Generated by Django 5.2.9 on 2026-02-27 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockups', '0022_alter_sobrediario_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipobalon',
            options={'ordering': ['-peso_neto_gas', 'tipo_gas'], 'verbose_name': 'Tipo de balón', 'verbose_name_plural': 'Tipos de balones'},
        ),
        migrations.AddField(
            model_name='tipobalon',
            name='tipo_gas',
            field=models.CharField(choices=[('normal', 'Normal'), ('catalitico', 'Catalítico'), ('aluminio', 'Aluminio')], default='normal', max_length=20, verbose_name='Tipo de gas'),
        ),
    ]
