# Generated by Django 5.2.9 on 2026-03-01 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockups', '0023_alter_tipobalon_options_tipobalon_tipo_gas'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaAccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('LOGIN_OK', 'Inicio de sesión exitoso'), ('LOGIN_FAIL', 'Intento de login fallido'), ('LOGOUT', 'Cierre de sesión'), ('USER_CREATE', 'Usuario creado'), ('USER_UPDATE', 'Usuario modificado'), ('USER_DELETE', 'Usuario eliminado'), ('PASSWORD_CHANGE', 'Contraseña cambiada'), ('PEDIDO_CREATE', 'Pedido creado'), ('PEDIDO_UPDATE', 'Pedido modificado'), ('PEDIDO_DELETE', 'Pedido eliminado'), ('PEDIDO_ESTADO', 'Estado de pedido cambiado'), ('PRECIO_UPDATE', 'Precio actualizado'), ('BALON_CREATE', 'Balón creado'), ('BALON_UPDATE', 'Balón modificado'), ('BALON_DELETE', 'Balón eliminado'), ('SOBRE_CREATE', 'Sobre creado'), ('SOBRE_CLOSE', 'Sobre cerrado'), ('SOBRE_UPDATE', 'Sobre modificado'), ('PERM_DENIED', 'Acceso denegado'), ('SUSPICIOUS', 'Actividad sospechosa'), ('EXPORT_DATA', 'Exportación de datos'), ('CONFIG_CHANGE', 'Configuración cambiada')], db_index=True, max_length=20, verbose_name='Tipo de acción')),
                ('username', models.CharField(blank=True, help_text='Guardamos el username por si el usuario es eliminado', max_length=150, verbose_name='Username (snapshot)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción detallada')),
                ('objeto_tipo', models.CharField(blank=True, help_text='Ej: Pedido, Usuario, TipoBalon', max_length=100, verbose_name='Tipo de objeto afectado')),
                ('objeto_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID del objeto afectado')),
                ('objeto_repr', models.CharField(blank=True, help_text='Snapshot del __str__ del objeto', max_length=255, verbose_name='Representación del objeto')),
                ('datos_anteriores', models.JSONField(blank=True, null=True, verbose_name='Datos anteriores (JSON)')),
                ('datos_nuevos', models.JSONField(blank=True, null=True, verbose_name='Datos nuevos (JSON)')),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha y hora')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['tipo', 'fecha'], name='mockups_aud_tipo_1d0ea2_idx'), models.Index(fields=['usuario', 'fecha'], name='mockups_aud_usuario_9bd1b9_idx'), models.Index(fields=['objeto_tipo', 'objeto_id'], name='mockups_aud_objeto__350f6f_idx')],
            },
        ),
    ]
