# Generated by Django 5.2.9 on 2026-03-02 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockups', '0024_add_auditoria_accion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(help_text='URL única del servicio push del navegador (truncado a 500 chars)', max_length=500, verbose_name='Endpoint URL')),
                ('p256dh', models.CharField(help_text='Clave pública del cliente para encriptación', max_length=255, verbose_name='Clave P256DH')),
                ('auth', models.CharField(help_text='Secret de autenticación del cliente', max_length=255, verbose_name='Auth Secret')),
                ('activa', models.BooleanField(default=True, help_text='Desactivar si la suscripción expira o falla', verbose_name='Activa')),
                ('user_agent', models.CharField(blank=True, help_text='Navegador/dispositivo del usuario', max_length=500, verbose_name='User Agent')),
                ('creada_el', models.DateTimeField(auto_now_add=True, verbose_name='Creada el')),
                ('actualizada_el', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Suscripción Push',
                'verbose_name_plural': 'Suscripciones Push',
                'ordering': ['-creada_el'],
            },
        ),
    ]
