# Generated by Django 5.1.3 on 2026-03-14 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockups', '0025_push_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipobalon',
            name='tipo_gas',
            field=models.CharField(choices=[('normal', 'Clásico'), ('catalitico', 'Catalítico'), ('aluminio', 'Aluminio')], default='normal', max_length=20, verbose_name='Tipo de gas'),
        ),
    ]
