# Generated by Django 5.1.3 on 2026-04-08 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockups', '0026_alter_tipobalon_tipo_gas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Usa el mismo texto que hoy se guarda en Pedido.sector para facilitar la futura migración.', max_length=100, unique=True, verbose_name='Nombre')),
                ('codigo', models.SlugField(blank=True, help_text='Identificador estable para integraciones futuras. Si lo dejas vacío, se genera automáticamente.', max_length=120, unique=True, verbose_name='Código interno')),
                ('zona', models.CharField(choices=[('sur', 'Sur'), ('norte', 'Norte'), ('otro', 'Otro / Sin zona')], default='otro', max_length=20, verbose_name='Zona')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Permite ordenar sectores en formularios y reportes futuros.', verbose_name='Orden')),
                ('creado_el', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('actualizado_el', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectores',
                'ordering': ['zona', 'orden', 'nombre'],
            },
        ),
    ]
