# Generated by Django 5.1.3 on 2026-04-08 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mockups', '0027_sector'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sector',
            options={'ordering': ['zona', 'nombre'], 'verbose_name': 'Sector', 'verbose_name_plural': 'Sectores'},
        ),
        migrations.RemoveField(
            model_name='sector',
            name='orden',
        ),
    ]
