# Generated by Django 5.1.3 on 2026-05-09 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockups', '0028_alter_sector_options_remove_sector_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='totp_activo',
            field=models.BooleanField(default=False, verbose_name='2FA activo'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='totp_secret',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Secreto TOTP'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='totp_ultimo_verificado',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Último código 2FA verificado en'),
        ),
    ]
