# Generated by Django 5.1.3 on 2026-06-21 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mockups', '0030_performance_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pedido',
            new_name='mockups_ped_sector_37b274_idx',
            old_name='mockups_ped_sector_8a1f2d_idx',
        ),
        migrations.RenameIndex(
            model_name='sobrediario',
            new_name='mockups_sob_fecha_c_da54a1_idx',
            old_name='mockups_sob_fecha_c_3e4b5a_idx',
        ),
        migrations.RenameIndex(
            model_name='sobrediario',
            new_name='mockups_sob_fecha_c_b292d1_idx',
            old_name='mockups_sob_fecha_t_6c7d8e_idx',
        ),
        migrations.RenameIndex(
            model_name='sobrediario',
            new_name='mockups_sob_trabaja_f16ee6_idx',
            old_name='mockups_sob_trabaj_f_9f0a1b_idx',
        ),
    ]
