# Generated by Django 5.1.3 on 2026-06-28 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockups', '0031_rename_mockups_ped_sector_8a1f2d_idx_mockups_ped_sector_37b274_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('direccion', models.CharField(blank=True, max_length=250, verbose_name='Dirección')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_el', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
            ],
            options={
                'verbose_name': 'Bodega',
                'verbose_name_plural': 'Bodegas',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='sector',
            name='nombre',
            field=models.CharField(help_text='Usa el mismo texto que hoy se guarda en Pedido.sector para facilitar la futura migración.', max_length=100, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='bodega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='mockups.bodega', verbose_name='Bodega'),
        ),
        migrations.AddField(
            model_name='sector',
            name='bodega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sectores', to='mockups.bodega', verbose_name='Bodega'),
        ),
        migrations.AddField(
            model_name='sobrediario',
            name='bodega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sobres', to='mockups.bodega', verbose_name='Bodega'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='bodega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabajadores', to='mockups.bodega', verbose_name='Bodega asignada'),
        ),
        migrations.AddConstraint(
            model_name='sector',
            constraint=models.UniqueConstraint(fields=('nombre', 'bodega'), name='unique_nombre_bodega'),
        ),
    ]
