# Generated by Django 5.1.3 on 2026-07-02 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockups', '0031_rename_mockups_ped_sector_8a1f2d_idx_mockups_ped_sector_37b274_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineapago',
            name='tipo_pago',
            field=models.CharField(choices=[('abono', 'Abono Caja'), ('transferencia', 'Transferencia'), ('visa', 'Visa'), ('cheque', 'Cheque'), ('efectivo', 'Efectivo'), ('pits', 'Pits'), ('monedas', 'Monedas'), ('cupon', 'Cupón'), ('otro', 'Otro')], default='otro', max_length=20, verbose_name='Tipo de Pago'),
        ),
    ]
