# Generated by Django 5.1.3 on 2026-09-27 20:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockups', '0032_nuevos_metodos_pago_sobres'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='descuento_unitario',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, help_text='Descuento en pesos por CADA balón. Se multiplica por la cantidad de la línea.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Descuento por unidad'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='descuento_total',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Suma de descuentos de las líneas. Se registra como pérdida aparte: no reduce ganancia_total.', max_digits=12, verbose_name='Descuento total'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='devuelto_el',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última devolución por camionero'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='devuelto_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_devueltos', to=settings.AUTH_USER_MODEL, verbose_name='Devuelto por'),
        ),
        migrations.AlterField(
            model_name='auditoriaaccion',
            name='tipo',
            field=models.CharField(choices=[('LOGIN_OK', 'Inicio de sesión exitoso'), ('LOGIN_FAIL', 'Intento de login fallido'), ('LOGOUT', 'Cierre de sesión'), ('USER_CREATE', 'Usuario creado'), ('USER_UPDATE', 'Usuario modificado'), ('USER_DELETE', 'Usuario eliminado'), ('PASSWORD_CHANGE', 'Contraseña cambiada'), ('PEDIDO_CREATE', 'Pedido creado'), ('PEDIDO_UPDATE', 'Pedido modificado'), ('PEDIDO_DELETE', 'Pedido eliminado'), ('PEDIDO_ESTADO', 'Estado de pedido cambiado'), ('PEDIDO_CANCEL', 'Pedido cancelado'), ('PEDIDO_DEVOLVER', 'Pedido devuelto al pool'), ('PEDIDO_DESCUENTO', 'Descuento aplicado a pedido'), ('PRECIO_UPDATE', 'Precio actualizado'), ('BALON_CREATE', 'Balón creado'), ('BALON_UPDATE', 'Balón modificado'), ('BALON_DELETE', 'Balón eliminado'), ('SOBRE_CREATE', 'Sobre creado'), ('SOBRE_CLOSE', 'Sobre cerrado'), ('SOBRE_UPDATE', 'Sobre modificado'), ('PERM_DENIED', 'Acceso denegado'), ('SUSPICIOUS', 'Actividad sospechosa'), ('EXPORT_DATA', 'Exportación de datos'), ('CONFIG_CHANGE', 'Configuración cambiada')], db_index=True, max_length=20, verbose_name='Tipo de acción'),
        ),
    ]
