# Generated by Django 5.1.3 on 2026-06-28 22:58

from django.db import migrations


def crear_bodega_default_y_backfill(apps, schema_editor):
    """Crea la bodega default y asigna todos los datos existentes a ella."""
    Bodega = apps.get_model('mockups', 'Bodega')
    Usuario = apps.get_model('mockups', 'Usuario')
    Sector = apps.get_model('mockups', 'Sector')
    Pedido = apps.get_model('mockups', 'Pedido')
    SobreDiario = apps.get_model('mockups', 'SobreDiario')

    # 1. Crear bodega default (única que existe hoy en producción)
    bodega_default, _ = Bodega.objects.get_or_create(
        nombre='KIM GAS Rancagua',
        defaults={'direccion': 'Rancagua', 'activo': True}
    )

    # 2. Asignar todos los usuarios existentes a la bodega default
    #    (admin puede quedar sin bodega para ver todo)
    Usuario.objects.filter(bodega__isnull=True).exclude(rol='admin').update(
        bodega=bodega_default
    )

    # 3. Asignar todos los sectores existentes a la bodega default
    Sector.objects.filter(bodega__isnull=True).update(bodega=bodega_default)

    # 4. Backfill Pedido.bodega
    #    Prioridad: registrador.bodega > entregador.bodega > bodega default
    for pedido in Pedido.objects.filter(bodega__isnull=True).select_related(
        'registrador', 'entregador'
    ):
        if pedido.registrador and pedido.registrador.bodega:
            pedido.bodega = pedido.registrador.bodega
        elif pedido.entregador and pedido.entregador.bodega:
            pedido.bodega = pedido.entregador.bodega
        else:
            pedido.bodega = bodega_default
        pedido.save(update_fields=['bodega'])

    # 5. Backfill SobreDiario.bodega
    #    tipo='camion': del trabajador
    #    tipo='bodega': del creado_por o default
    for sobre in SobreDiario.objects.filter(bodega__isnull=True).select_related(
        'trabajador', 'creado_por'
    ):
        if sobre.tipo == 'camion' and sobre.trabajador and sobre.trabajador.bodega:
            sobre.bodega = sobre.trabajador.bodega
        elif sobre.creado_por and sobre.creado_por.bodega:
            sobre.bodega = sobre.creado_por.bodega
        else:
            sobre.bodega = bodega_default
        sobre.save(update_fields=['bodega'])


def revertir_backfill(apps, schema_editor):
    """Revierte el backfill (pone bodega en NULL para todos)."""
    Usuario = apps.get_model('mockups', 'Usuario')
    Sector = apps.get_model('mockups', 'Sector')
    Pedido = apps.get_model('mockups', 'Pedido')
    SobreDiario = apps.get_model('mockups', 'SobreDiario')

    Usuario.objects.all().update(bodega=None)
    Sector.objects.all().update(bodega=None)
    Pedido.objects.all().update(bodega=None)
    SobreDiario.objects.all().update(bodega=None)


class Migration(migrations.Migration):

    dependencies = [
        ('mockups', '0032_multi_bodega_fase1'),
    ]

    operations = [
        migrations.RunPython(crear_bodega_default_y_backfill, revertir_backfill),
    ]
