# Generated by Django 5.1.3 on 2026-09-28 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockups', '0033_pedido_descuento_linea_y_devolucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoriaaccion',
            name='tipo',
            field=models.CharField(choices=[('LOGIN_OK', 'Inicio de sesión exitoso'), ('LOGIN_FAIL', 'Intento de login fallido'), ('LOGOUT', 'Cierre de sesión'), ('USER_CREATE', 'Usuario creado'), ('USER_UPDATE', 'Usuario modificado'), ('USER_DELETE', 'Usuario eliminado'), ('PASSWORD_CHANGE', 'Contraseña cambiada'), ('PEDIDO_CREATE', 'Pedido creado'), ('PEDIDO_UPDATE', 'Pedido modificado'), ('PEDIDO_DELETE', 'Pedido eliminado'), ('PEDIDO_ESTADO', 'Estado de pedido cambiado'), ('PEDIDO_CANCEL', 'Pedido cancelado'), ('PEDIDO_DEVOLVER', 'Pedido devuelto al pool'), ('PEDIDO_DESCUENTO', 'Descuento aplicado a pedido'), ('PRECIO_UPDATE', 'Precio actualizado'), ('BALON_CREATE', 'Balón creado'), ('BALON_UPDATE', 'Balón modificado'), ('BALON_DELETE', 'Balón eliminado'), ('SOBRE_CREATE', 'Sobre creado'), ('SOBRE_CLOSE', 'Sobre cerrado'), ('SOBRE_UPDATE', 'Sobre modificado'), ('CONTEO_CREATE', 'Conteo de balones creado'), ('CONTEO_UPDATE', 'Conteo de balones modificado'), ('PERM_DENIED', 'Acceso denegado'), ('SUSPICIOUS', 'Actividad sospechosa'), ('EXPORT_DATA', 'Exportación de datos'), ('CONFIG_CHANGE', 'Configuración cambiada')], db_index=True, max_length=20, verbose_name='Tipo de acción'),
        ),
        migrations.CreateModel(
            name='ConteoDiarioBalon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True, verbose_name='Fecha del conteo')),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('actualizado_el', models.DateTimeField(auto_now=True)),
                ('nota', models.TextField(blank=True, verbose_name='Observaciones del día')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conteos_balones_creados', to=settings.AUTH_USER_MODEL, verbose_name='Conteo creado por')),
            ],
            options={
                'verbose_name': 'Conteo diario de balones',
                'verbose_name_plural': 'Conteos diarios de balones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='LineaConteoBalon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_inicial_llenos', models.PositiveIntegerField(default=0, verbose_name='Llenos al iniciar el día')),
                ('stock_inicial_vacios', models.PositiveIntegerField(default=0, verbose_name='Vacíos al iniciar el día')),
                ('llenos_entran', models.PositiveIntegerField(default=0, verbose_name='Llenos que entran')),
                ('llenos_salen', models.PositiveIntegerField(default=0, verbose_name='Llenos que salen')),
                ('vacios_entran', models.PositiveIntegerField(default=0, verbose_name='Vacíos que entran')),
                ('vacios_salen', models.PositiveIntegerField(default=0, verbose_name='Vacíos que salen')),
                ('balon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mockups.tipobalon', verbose_name='Tipo de balón')),
                ('conteo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='mockups.conteodiariobalon')),
            ],
            options={
                'verbose_name': 'Línea de conteo de balones',
                'verbose_name_plural': 'Líneas de conteo de balones',
                'ordering': ['balon__peso_neto_gas'],
                'unique_together': {('conteo', 'balon')},
            },
        ),
    ]
