# Generated by Django 5.1.3 on 2026-10-08 00:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockups', '0034_conteo_diario_balones'),
    ]

    operations = [
        migrations.CreateModel(
            name='UbicacionCamion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitud')),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitud')),
                ('precision_m', models.FloatField(blank=True, null=True, verbose_name='Precisión (m)')),
                ('velocidad', models.FloatField(blank=True, null=True, verbose_name='Velocidad (m/s)')),
                ('bateria', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Batería (%)')),
                ('capturado_el', models.DateTimeField(verbose_name='Capturada el')),
                ('recibido_el', models.DateTimeField(auto_now_add=True, verbose_name='Recibida el')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones', to=settings.AUTH_USER_MODEL, verbose_name='Camionero')),
            ],
            options={
                'verbose_name': 'Ubicación del camión',
                'verbose_name_plural': 'Ubicaciones del camión',
                'ordering': ['-capturado_el'],
                'indexes': [models.Index(fields=['trabajador', 'capturado_el'], name='mockups_ubi_trabaja_16bdc1_idx')],
            },
        ),
    ]
