# Generated by Django 5.1.3 on 2026-07-13 18:25

import mockups.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mockups', '0034_nuevos_metodos_pago_sobres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='totp_secret',
            field=mockups.fields.EncryptedTextField(blank=True, max_length=255, null=True, verbose_name='Secreto TOTP'),
        ),
    ]
