# Generated by Django 5.1.3 on 2026-10-09
#
# Alta del canal de notificaciones de la app nativa (docs/API_MOVIL.md §7.7).
# Es aditiva: no toca `PushSubscription` (Web Push de la PWA) ni ninguna tabla
# existente.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockups', '0035_ubicacioncamion'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispositivoPush',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(help_text='Identificador del dispositivo que entrega Firebase (nunca se registra en logs)', max_length=255, unique=True, verbose_name='Token FCM')),
                ('plataforma', models.CharField(choices=[('android', 'Android')], default='android', max_length=16, verbose_name='Plataforma')),
                ('app_version', models.CharField(blank=True, default='', max_length=32, verbose_name='Versión de la app')),
                ('activa', models.BooleanField(default=True, help_text='Se desactiva cuando FCM responde que el token ya no existe', verbose_name='Activa')),
                ('creado_el', models.DateTimeField(auto_now_add=True, verbose_name='Registrado el')),
                ('actualizado_el', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos_push', to=settings.AUTH_USER_MODEL, verbose_name='Camionero')),
            ],
            options={
                'verbose_name': 'Dispositivo con notificaciones',
                'verbose_name_plural': 'Dispositivos con notificaciones',
                'ordering': ['-actualizado_el'],
            },
        ),
    ]
