# Generated by Django 5.1.3 on 2026-10-09
#
# FCM migró de los *registration tokens* al Firebase Installation ID (FID), y la
# v1 de la API **deprecia `token` a favor de `fid`** (el `token` acepta un FID
# solo durante la transición). El campo nació como `token` la mañana del
# 2026-10-09 y ya estaba aplicado en la base local, así que el renombre va como
# migración nueva en vez de reescribir la 0036.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockups', '0036_dispositivopush'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dispositivopush',
            old_name='token',
            new_name='fid',
        ),
        # El renombre de columna no toca las etiquetas del campo: sin este
        # AlterField el `verbose_name` quedaría diciendo "Token FCM" en el admin.
        migrations.AlterField(
            model_name='dispositivopush',
            name='fid',
            field=models.CharField(
                help_text='Firebase Installation ID del teléfono (nunca se registra completo en logs)',
                max_length=255,
                unique=True,
                verbose_name='Installation ID (FID)',
            ),
        ),
    ]
