# Generated by Django 5.1.3 on 2026-10-09
#
# Vuelta a `token`: el plugin de Flutter (firebase_messaging 16.7.0) todavía **no**
# expone los Firebase Installation IDs —`onRegistered` y `register()` no existen—,
# así que el cliente solo puede entregar un *registration token*. La v1 de FCM
# deprecia `token` a favor de `fid`, pero lo soporta durante la transición, que es
# donde estamos. La 0037 hizo el renombre inverso por un supuesto que el código
# del cliente desmintió.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockups', '0037_rename_token_fid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dispositivopush',
            old_name='fid',
            new_name='token',
        ),
        migrations.AlterField(
            model_name='dispositivopush',
            name='token',
            field=models.CharField(
                help_text='Registration token de FCM del teléfono (nunca se registra completo en logs)',
                max_length=255,
                unique=True,
                verbose_name='Token de FCM',
            ),
        ),
    ]
